cmake_minimum_required(VERSION 3.20)
project(TestProject LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(MY_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
set(MY_BINARY_DIR "${MY_SOURCE_DIR}/bin")
set(MY_BUILD_DIR "${MY_SOURCE_DIR}/build")
set(MY_CMAKE_DIR "${MY_SOURCE_DIR}/cmake")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${MY_BINARY_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${MY_BINARY_DIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${MY_BINARY_DIR}")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${MY_BINARY_DIR}/Debug")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${MY_BINARY_DIR}/Release")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${MY_BINARY_DIR}/MinSizeRel")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${MY_BINARY_DIR}/RelWithDebInfo")

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${MY_BINARY_DIR}/Debug")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${MY_BINARY_DIR}/Release")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL "${MY_BINARY_DIR}/MinSizeRel")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${MY_BINARY_DIR}/RelWithDebInfo")

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${MY_BINARY_DIR}/Debug")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${MY_BINARY_DIR}/Release")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL "${MY_BINARY_DIR}/MinSizeRel")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO "${MY_BINARY_DIR}/RelWithDebInfo")

include(${MY_CMAKE_DIR}/TestProject.cmake)

add_subdirectory(src/App)
add_subdirectory(src/Static)
add_subdirectory(src/Dynamic)
